# Generated by Django 4.2.6 on 2023-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TANK', 'Танки'), ('HEAL', 'Хилы'), ('DDDD', 'ДД'), ('TRDE', 'Торговцы'), ('GMGM', 'Гилдмастеры'), ('QUST', 'Квестгиверы'), ('BLCK', 'Кузнецы'), ('TLOR', 'Кожевники'), ('POTM', 'Зельевары'), ('WIZZ', 'Мастера заклинаний')], max_length=4, unique=True),
        ),
    ]
