# Generated by Django 4.2.6 on 2023-10-14 15:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_slug_alter_post_post_body_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
